### ISSUE TITLE
Problems of use

### ISSUE THREAD

**Issue by songgw** [jeeeyul/eclipse-themes#234]
Hi:
     I want to know, How can i change the view background color?
    
    thank you
    songgw

**Comment by jeeeyul** [comment]
That is not recommended. See [Using Black Theme](https://github.com/jeeeyul/eclipse-themes/wiki/Using-Black-Theme).

if you want to try, use below css into Custom CSS:
``` CSS
.MPart, .MPart Tree, .MPart Table, .MPart Canvas {
	background-color: red;
}
```
